// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNyPJCpPtWCIDZkO5_VeF_QKYYsUJbfk',
    appId: '1:540492691511:web:05f5907e6db367b87267b2',
    messagingSenderId: '540492691511',
    projectId: 'insta-clone-4b0d1',
    authDomain: 'insta-clone-4b0d1.firebaseapp.com',
    storageBucket: 'insta-clone-4b0d1.firebasestorage.app',
    measurementId: 'G-XDQ1YDGQ0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppqqBRnCmIlj2FHtWkfRr4NpnWYHKtlU',
    appId: '1:540492691511:android:901c505e2008a3bf7267b2',
    messagingSenderId: '540492691511',
    projectId: 'insta-clone-4b0d1',
    storageBucket: 'insta-clone-4b0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6PPJIUYTo4wr2QPMoSVBcfSvhPcEfwQU',
    appId: '1:540492691511:ios:93dd01198d6c2e057267b2',
    messagingSenderId: '540492691511',
    projectId: 'insta-clone-4b0d1',
    storageBucket: 'insta-clone-4b0d1.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );
}
